// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package models

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RssServerClient is the client API for RssServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RssServerClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type rssServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRssServerClient(cc grpc.ClientConnInterface) RssServerClient {
	return &rssServerClient{cc}
}

func (c *rssServerClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/models.RssServer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RssServerServer is the server API for RssServer service.
// All implementations must embed UnimplementedRssServerServer
// for forward compatibility
type RssServerServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	mustEmbedUnimplementedRssServerServer()
}

// UnimplementedRssServerServer must be embedded to have forward compatible implementations.
type UnimplementedRssServerServer struct {
}

func (UnimplementedRssServerServer) Ping(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRssServerServer) mustEmbedUnimplementedRssServerServer() {}

// UnsafeRssServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RssServerServer will
// result in compilation errors.
type UnsafeRssServerServer interface {
	mustEmbedUnimplementedRssServerServer()
}

func RegisterRssServerServer(s grpc.ServiceRegistrar, srv RssServerServer) {
	s.RegisterService(&_RssServer_serviceDesc, srv)
}

func _RssServer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RssServerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.RssServer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RssServerServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RssServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.RssServer",
	HandlerType: (*RssServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RssServer_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/feed.proto",
}
